#!/usr/bin/env bash
# A rofi -dmenu prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.

unmountusb() {
	chosen=$(echo "$drives" | rofi -dmenu -i -p "Unmount which drive" | awk '{print $1}')
	[ -z "$chosen" ] && exit
	udisksctl unmount -b "$chosen"
}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | grep -v .steamgames | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s %s (%s)\n",$1,$4,$3}')

if [ -z "$drives" ]; then
	notify-send "No drives to unmount" && exit
else
	unmountusb
fi
