#!/bin/sh

# Check for xclip
xclip -h >/dev/null || exit

chosen=$(grep -v "#" ~/.local/share/emoji | rofi -dmenu -i -p 'Emojis')

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard" &
