#!/usr/bin/env bash
# Gives a rofi prompt to mount unmounted drives.
# Ignores internal nvme drives

mountusb() {
	chosen="$(echo "$usbdrives" | rofi -dmenu -i -p "Mount which drive" | awk '{print $1}')"
	udisksctl mount -b "$chosen"
}

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v -e nvme | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
	notify-send "No drives detected" && exit
else
	mountusb
fi
